stages:
  - build
  - deploy

build:
  stage: build

  only:
    - master

  script:
    - npm install --verbose
    - npm run build

  artifacts:
    paths:
      - ./dist/


deploy:
  stage: deploy

  only:
    - master

  variables:
    dir_root: /var/www/
    webspace: oleb/vue/

  script:
    - "target=$dir_root$webspace"
    - "echo \"Deploying to: $target\""
    - "rsync -rlvc --chown gitlab-runner:www-data ./dist/ $target"
