stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:latest
  tags: 
    - docker

  only:
    - master
    - merge_requests
    - triggers
    - web
    - schedules

  cache:
    paths:
      - node_modules/

  script:
    - npm install
    - npm run build
    - "echo \"<span>This is Build
        <a href=\\\"https://git.oleb.it/obittner/oleb.it/commit/$CI_COMMIT_SHA\\\" target=\\\"_blank\\\">
        <b>${CI_COMMIT_SHA:0:8}</b>: $CI_COMMIT_TITLE</a>\" > ./dist/cmd_data/version.html"

  artifacts:
    paths:
      - ./dist/
    expire_in: '6h'


unit tests:
  stage: test
  image: node:latest
  tags: 
    - docker

  only:
    - master
    - merge_requests
    - triggers
    - web
    - schedules

  cache:
    paths:
      - node_modules/

  script:
    - npm install
    - npm run test -- --coverage

  artifacts:
    reports:
      junit: junit.xml


deploy:
  stage: deploy
  tags:
    - host

  only:
    - master
    - triggers

  environment:
    name: production
    url: https://oleb.it/

  variables:
    dir_root: /var/www/
    webspace: oleb/vue/

  script:
    - "target=$dir_root$webspace"
    - "echo \"Deploying to: $target\""
    - "rsync -rlvc --delete ./dist/ $target"
    - "echo \"<br>This Version was deployed <b>$(date '+%Y %b %d %H:%M')</b></span>\" >> $target/cmd_data/version.html"
    - "chgrp -hR www-data $target/*"
